[package]
name = "SeiveOfEratosthenes"
version = "0.1.0"
authors = ["daniel"]
edition = "2022"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bit-vec = "0.6"
